modules/app_components/menu.py

Allows code to be executed when the menu item is being changed.
My use case is to preview LED effects without having to press the confirm button and show a nice preview of the colour palette on the menu.

Add menu item change handler

---

sim/fakes/ctx.py

I fixed the rgba method to have values from 0-1.0 for alpha channel (as I think is customary) in the ctx library and added the error handling that there was a todo for.

Improve ctx with fixed alpha channel

---

sim/fakes/ujson.py

This adds in a very simple mock for `ujson` which I think is a built-in MicroPython library for which mocks are missing.

Add ujson fake

---

modules/system/launcher/app.py

Launcher raises exception when trying to launch apps in `/apps`. It can find and display them just fine though.

Launcher: fix /apps not being included in module path.

---

modules/system/launcher/app.py

Reloading the menu set a new menu, but the old one still exists and was also reacting to button presses, leading to chaos when multiple instances tried launching apps.

App launcher: clean up menu on reload

---

modules/firmware_apps/settings_app.py

Text-shaped values can now be edited, WiFi settings can be reset to EMF defaults.
CURRENTLY sometimes crashes when starting the app, unsure what it is:
```
Creating app firmware_apps.settings_app.SettingsApp...
Registered async event handler for ButtonDownEvent: SettingsApp - _button_handler
Traceback (most recent call last):
File "system/scheduler/__init__.py", line 220, in _render_task
File "firmware_apps/settings_app.py", line 103, in draw
File "app_components/layout.py", line 119, in draw
File "app_components/layout.py", line 148, in centred_component
NameError: local variable referenced before assignment
Removing launcher cache for firmware_apps.settings_app.SettingsApp
Stopping app: <RequestStopAppEvent object at 3c28bc20>
Stopping background <SettingsApp object at 3c289b60> …
```

[WIP] Improved settings app

---

flasher/index.html

<li>1. Hold <b>boop</b> while plugging USB into <b>USB in</b>.</li>
<li>2. Keep holding <b>boop</b> until you click <b>Connect</b> and click on the badge COM port.</li>
<li>3. Let go of the <b>boop</b></li>
<li>4. Select <b>Install Tildagon</b>, and wait.</li>

Add documentation instructions to badge flasher page

---

README.md

Add `--rm` to the docker commandline to not leave old unused containers around. All the state is in the mapped folders, so they only waste disk space (and caused some weird btrfs issues on my system)

Update README.md docker instructions

---

modules/system/ota/ota.py

Rebooting? Is that even a word?
Fixed the status message output to correctly say "Rebooping"

Fix typographical error in "Rebooping" message

---

flasher/index.html

Bootloader doesn't work if the device is already powered on when plugging in USB

Improve bootloader activation instructions

---

modules/firmware_apps/app_store.py

The pull request fixes two issues related to the app store.
The first commit removes a non-resolving URL that was causing the app store refreshing to take more than 15 seconds.
The second commit prevents the flashing of an "Unknown error" message when the index is loaded but the main menu is not created.

Fix app store loading and error messages

---

sim/fakes/machine.py

Attempting to fix #116 . I don't know if this has any other consequences tbh but the hexpansion code relies on Pin 0 returning true. See https://github.com/emfcamp/badge-2024-software/blob/main/modules/frontboards/twentyfour.py#L39

Change default pin value for simulator

---

modules/app_components/dialog.py
modules/app_components/tokens.py

When I got home and had to type in my WiFi credentials using the old keyboard, it took me so long I decided to crack out my laptop and run code to do it instead. This PR is a bit of an attempt to improve the speed of typing text in on the keyboard.
Each button on the badge corresponds to a group of letters, so the up button does letters **a** to **f**, once you press that, the buttons are reassigned letters through that range, so the up button now becomes **a**. The numbers are part of the uppercase letters (accessed with shift or caps) to keep the keyboard simpler. There's a 'meta' menu with backspace, shift, caps lock, symbols and cancel.
The keyboard is compatible with how the old one is used, so no other code needs to be changed.
As I wrote a function to label the buttons, I added …

Improved keyboard

---

modules/firmware_apps/settings_app.py

This PR masks the password shown in the settings app as well as on the keyboard when entering.
Fixes #105

Mask wifi password in settings app

---

modules/firmware_apps/app_store.py

Python's tarfile doesn't append a "/" to directory names like MicroPython does, so the root directory detection fails. Normalise the names by removing the "/" and then adding it back when returning the root directory name.

Fix app installation on the simulator

---

components/flow3r_bsp/flow3r_bsp_imu.c
components/flow3r_bsp/flow3r_bsp_imu.h
components/st3m/st3m_imu.c
components/st3m/st3m_imu.h
drivers/tildagon_helpers/mp_imu.c

Enables the step counter in the BMI270, exposing a `step_counter_read` method as part of the IMU API.
Example usage:
```python
import app
import imu
from events.input import Buttons, BUTTON_TYPES
class ExampleApp(app.App):
def __init__(self):
self.button_states = Buttons(self)
self.acc_read = None
self.steps_read = None
def update(self, delta):
if self.button_states.get(BUTTON_TYPES["CANCEL"]):
self.button_states.clear()
self.minimise()
else:
self.steps_read = imu.step_counter_read()
def draw(self, ctx):
ctx.save()
ctx.rgb(0.2,0,0).rectangle(-120,-120,240,240).fill()
if self.steps_read:
ctx.rgb(1,0,0).move_to(-80,-40).text("steps:\n{}\n".format(self.steps_read))
else:
ctx.rgb(1,0,0).move_to(-80,0).text("no readings yet")
ctx.restore()
__app_export__ = ExampleApp
```

Add step counter to IMU API

---

modules/firmware_apps/app_store.py

Fix for issue #135 so that you can install apps using app.mpy files as well as those using app.py via the app store.
Already works for direct install, but at present the validation of the downloaded tarball fails as it this process only checks for the presence of app.py

app_store install check for .mpy file as well as .py

---

drivers/gc9a01/display.c

As suggested by pippin, this moves the ctx framebuffer to SRAM to avoid contention on the cache lines, which improves performance of v1.7.0 while the render task is in MP

display: move framebuffer to SRAM to avoid cache line contention

---

modules/app_components/notification.py

The insertion events are not properly showing the hexpansion name. This confused people at camp, thinking the green border was part of the GCHQ.net app. This simplifies the code to use the port=0 code with the rotation applied, instead of trying to re-rotate

Fix hexpansion insertion event text

---

modules/system/scheduler/__init__.py

Do not draw the whole foreground stack, only the last one and overlays. People aren't writing apps that draw partial screens, and this prevents us having to re-render the menu constantly.
Refs: #100

Only draw the focused and always-on-top apps

---

.github/workflows/build.yml

Fixes #128 
Tested in a fork, but YMMV (see https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md for potential pitfalls I may have missed here, but I think this is as straightforward as it seems)

Update GH Action runner to resolve deprecations

---

.github/workflows/build.yml
modules/firmware_apps/settings_app.py
modules/system/ota/ota.py

This improves the OTA app to parse version numbers better, with the following rules:
- Major, Minor and Patch versions are parsed as numbers rather than strings, so v1.10.0 > v1.9.0
- Development versions where there's a 'number of commits ahead' item are counted as ahead of the version they're on
- If there's an rc after the patch number, it's treated as ahead of the previous version, so v1.9.0 < v1.10.0rc1 < v1.10.0rc1-1-aaaaaa < v1.10.0 < v1.10.0-1-aaaaaa
If there is an rc in the tag name, it won't overwrite the `latest` release, it will overwrite the `preview` release.
The setting `update_channel` will work as normal if unset or set to `latest`. Set it to `preview` to get release candidates.

Add support for a beta channel

---

.github/workflows/build.yml
components/st3m/host-tools/version.py
modules/system/ota/ota.py
tildagon/mpconfigboard.cmake

This changes the use of git describe to generate (v-prefixed) semver versions, moving the build information to a + block. It also enhances the version parsing in ota to more closely match semver.
This should make the `v1.8.0-rc.1` tag format work.

Improved use of semver

---

drivers/tildagon_power/tildagon_power.h

Increases the minimum battery voltage to the 3 volt minimum specified in its datasheet, as discussed in issue #175

Increase VBATMIN to 3 volts

---

sim/fakes/egpio.py
sim/fakes/tildagonos.py

Create egpio.py fake

---

drivers/tildagon_power/bq25895/bq25895.c
drivers/tildagon_power/mp_power.c
drivers/tildagon_power/tildagon_power.h

fixes issue #83 
rework the battery level algorithm to be use different values for discharge and charge states and in the charge state use charge current profiles based on input current limits to calculate SOC. Reduce the charge termination current to 64mA to allow battery to charge to 4.2V.

Improve battery level

---

modules/firmware_apps/app_store.py
modules/system/eventbus.py

Allow to install multiple apps

---

modules/firmware_apps/app_store.py
modules/system/launcher/app.py

Fixes #124.
Because we currently don't store the version (we do in the toml but adding regex checking into this feels error-prone), the first time a user runs upgrade they'll get all installed apps. The versions then get stored in the metadata.json and from there it will only list apps if there are apps to be updated.
This is easier to test if you rebase off of #167

Allow app updating

---

drivers/tildagon_power/fusb302b/fusb302b_pd.c
drivers/tildagon_power/fusb302b/fusb302b_pd.h
drivers/tildagon_power/tildagon_power.c

enable pd comms to add pd supply capabilities to power.SupplyCapabilities(), restrict the maximum voltage requested to 5V due to hardware limits and cap current request to max input current.

enable pd comms

---

modules/firmware_apps/app_store.py

This splits the app store's listing of apps into categories. This is done based on the app store index and the categories are set by the app developers. Unfortunately, there's still a lot of them under "Badge", but it makes it slightly easier to navigate.

Add app store category menu

---

modules/firmware_apps/poweroff.py

Turn off LEDs and Hexpansions when the badge is plugged in and powered off. requested in issue #109 but this doesn't allow charging, but does make the badge feel like it's been shutdown. An App might be better solution to the issue.

turn off LEDs and hexpansions on power off

---

modules/scripts/prepare_eeprom.py

This is a large (512kbit - 64kbyte) eeprom that seems to work fine
I built a hexpansion with this EEPROM (https://www.digikey.com/en/products/detail/onsemi/CAT24C512WI-GT3/2683757) - this PR adds an example of how to use it.
This could be useful for those who need more space - it's the largest the 16-bit addresses can deal with!

prepare_eeprom.py: Add CAT24C512 header example

---

.github/workflows/build.yml
flasher/manifest.json

We currently don't support IMPROV, but it keeps accidentally getting turned on when connecting to the badge over webserial.  This prevents the webserial terminal from being used, as it appends `IMPROV` to random characters
This MR should force it to be disabled.

web flasher: actively disable improv

---

drivers/tildagon_power/mp_power.c

Update power supply capability functions to use float for voltage values.
When using the voltage values from `power.SupplyCapabilities()` they were being displayed as int instead of floats, 4.90V would be displayed as 4.00V.
With this change it correctly displays as 4.90V
```python
import power
SupplyCapabilities = power.SupplyCapabilities()[0]
ctx.move_to(0, 0).text("Voltage: {:.2f}".format(SupplyCapabilities[2]) + "V")
```

Update power supply capability functions to use float for voltage values

---

modules/firmware_apps/app_store.py
modules/system/launcher/app.py

This moves some code from the background task to the main task, and refactors it to allow use of async methods. This looks like these tasks were in background from the idea that the background task runs 'in the background', rather than runs 'when the app is in the background'.
There are two calls that use requests.get, which block the update task. By refactoring slightly to use async, we can use async_helpers.unblock to move them to a thread.

Improve async compatibility of app store

---

modules/system/ota/ota.py

Pull the current configured pattern brightness and apply it to the OTA progress indicator, to avoid the lights looking surprisingly bright during updates.

Use pattern brightness on OTA progress display

---

modules/app_components/background.py
modules/firmware_apps/settings_app.py

This makes two improvements to the background functionality:
1. The settings app re-scans for backgrounds when it's foregrounded. Without this, if a user has already opened the settings app since boot, new backgrounds won't be added after installation until rebooping
2. Add crash handling code around the background draw method, so crashes here are contained to the background runner, rather than bringing down the launcher

Improvements to background functionality reliability
